@host=https://localhost:7061
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYmNkMDgwZi0wNjU2LTQxYWMtYTY5NS0xNDgzMGQyYWVhYmQiLCJnaXZlbl9uYW1lIjoibGFpLm5ndXllbiIsImp0aSI6IjhmZjA3ZWJhLTkyNzEtNGU4ZS05NTAwLWEzOGQ2MzUwNWM1NiIsImV4cCI6MTY4OTEzNzgzNywiaXNzIjoiQXBlcmlhIiwiYXVkIjoiQXBlcmlhIn0.zhRHKlqBJWLaS46sRlmd-LWY3g5KAyC8pnyWdltvmwU
@accountId=82db48c6-9889-4a03-8153-4334a948d9ca

PUT {{host}}/bank-accounts/{{accountId}}/transfer
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "toAccountId": "c2215e2c-3450-4680-b31e-205f37c7f09f",
  "amount": 1000,
  "reference": "ReceiptNo: xxxx"
}